apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-unsigned
  namespace: demo
  labels:
    app: demo-app
    version: unsigned
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: unsigned
  template:
    metadata:
      labels:
        app: demo-app
        version: unsigned
    spec:
      containers:
        - name: app
          # This image is NOT signed
          # Kyverno should BLOCK this deployment
          image: localhost:5000/supply-chain-demo:1.0.0-unsigned
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "1.0.0-unsigned"
